In [1]:
import numpy as np
from scipy import stats

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basicoperations like:
- a) Addition of 2 in all the element
- b) Multiply 3 with all the elements
- c) Divide every element by 2 


In [2]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr+2

array([2, 3, 4, 5, 6])

In [4]:
arr*3

array([ 0,  3,  6,  9, 12])

In [5]:
arr/2

array([0. , 0.5, 1. , 1.5, 2. ])

Q.2 Questions on Basic NumPy Array:
- a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
- b) Find the most frequent value and their indice(s) in the following arrays:
    - i. x = np.array([1,2,3,4,5,1,2,1,1,1])
    - ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 


In [6]:
reversed(arr)
reversed_arr = arr[::-1]
reversed_arr

array([4, 3, 2, 1, 0])

In [7]:
arr=np.array([1,2,3,4,1,2,3,1,1,1,2,3,1,4,2])

In [8]:
modeval=stats.mode(arr)
print(f"The mode is {modeval[0]} and its frequency is {modeval[1]} and its occurance is ")

The mode is 1 and its frequency is 6 and its occurance is 


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
- a) Access 1st row, 2nd column
- b) Access 3rd row, 1st column 

In [9]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr[0][1]

20

In [11]:
arr[-1][0]

70

Q.4 Write program to create an 1-D NumPy array named Your Name with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute? 


In [12]:
sajid=np.linspace(10,100,25)
sajid

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [13]:
sajid.ndim

1

In [14]:
sajid.shape

(25,)

In [15]:
sajid.size

25

In [16]:
sajid.dtype

dtype('float64')

In [17]:
sajid.nbytes

200

In [18]:
sajid.reshape(1,-1)

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
         40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
         70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
        100.  ]])

In [19]:
sajid.T

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>.

In [20]:
ucs420_sajid=np.array([10,20,20,40,50,60,70,80,90,15,20,35]).reshape(3,4)
ucs420_sajid

array([[10, 20, 20, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [21]:
ucs420_sajid.mean()

42.5

In [22]:
np.median(ucs420_sajid)

37.5

In [23]:
ucs420_sajid.max()

90

In [24]:
ucs420_sajid.min()

10

In [25]:
np.unique(ucs420_sajid)

array([10, 15, 20, 35, 40, 50, 60, 70, 80, 90])

In [26]:
resized_ucs420_sajid=ucs420_sajid.T
resized_ucs420_sajid

array([[10, 50, 90],
       [20, 60, 15],
       [20, 70, 20],
       [40, 80, 35]])